name: Validate docker-compose

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Validate prometheus.yml
        run: docker run --rm -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus:latest promtool check config /etc/prometheus/prometheus.yml
